apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpdweb1-pv-claim
  labels:
    app: httpd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
